### ISSUE TITLE
firebase_admin_interop 0.0.1 depends on version ^0.0.4

### ISSUE THREAD

**Issue by DrivEddy** [pulyaevskiy/firebase-admin-interop#4]
Any idea?

```
ERR : Package node_interop has no versions that match >=0.0.4 <0.1.0 derived from:
    | - firebase_admin_interop 0.0.1 depends on version ^0.0.4
```

**Comment by pulyaevskiy** [comment]
Curious how your `pubspec.yaml` looks like? Just verified it on a new empty project and it should work.

Also:
- You might also check `0.1.0-beta` versions
- If you have Dart 2.0.0-dev SDK installed: I will be publishing first `1.0.0-dev` version soon with a lot of changes and improvements.

**Comment by DrivEddy** [comment]
Thats how my spec looks like.

Ill check `1.0.0-dev` once its published

```
description: "An easily-extensible web server framework in Dart."
homepage: "https://github.com/angel-dart/angel"
name: "platform"
publish_to: "none"


dependencies: 
  angel_auth: "any"                       # ^1.1.0-alpha
  angel_configuration: "any"              #"^1.1.0-alpha"
  angel_cors: "any"                       #"^1.0.0"
  angel_framework: "any"                  # "^1.1.0-alpha"
  angel_jael: "any"                       #"^1.0.0-alpha"
  angel_serialize: "any"                  #"^1.0.0-alpha"
  angel_static: "any"                     #"^1.3.0-alpha"
  angel_validate: "any"                   #"^1.0.0"
  angel_orm: "any"
  angel_migration: "any"


dev_dependencies: 
  angel_hot: "any"                        #"^1.1.0-alpha
  angel_serialize_generator: "any"        # ^1.0.0-alpha
  angel_orm_generator: "any"
  angel_migration_runner: "any"
  angel_test: "any"                       #^1.1.0-alpha"
  build_runner: "any"                     #"^0.5.0
  console: "any"                          # ^2.2.4
  grinder: "any"                          # ^0.8.0
  test: "any"                             # ^0.12.13


environment: 
  sdk: ">=1.19.0"


transformers:
  - "angel_configuration"

```
