### ISSUE TITLE
 firebase_admin_interop builds are failing

### ISSUE THREAD

**Issue by sultanmyrza** [pulyaevskiy/firebase-admin-interop#62]
I got working example with `firebase_functions_interop` after I add `firebase_admin_interop` builds are failing
pubspec.yaml
```
name: functions
version: 1.0.0
environment:
  sdk: ">=2.8.0 <3.0.0"
dependencies:
  firebase_functions_interop: ^1.0.2
  firebase_admin_interop: ^1.0.0
  node_interop: ^1.2.0

dev_dependencies:
  build_runner: ^1.0.0
  build_node_compilers: ^0.2.0
```

`pub run build_runner build --output=build`
gives error
```
Error: Null safety features are disabled for this library.
  final String? name;
```

`flutter doctor -v`
```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en)
    • Flutter version 1.23.0-18.1.pre at /Users/sultanmyrza/flutter
    • Framework revision 198df796aa (5 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)
```
